### ISSUE TITLE
Wokkel is not working with lastest version of Twisted (21.02)

### ISSUE THREAD

**Issue by goffi-contrib** [ralphm/wokkel#31]
Hello,

Wokkel is not working with latest version of Twisted due to the use of `twisted.python.compat._PY3`. Indeed Twisted has dropped Python 2.7 support in this version, and thus removed `_PY3`.

Thanks

**Comment by micheloosterhof** [comment]
```
Python 3.9.0 (default, Oct  8 2020, 06:18:59) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wokkel import muc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michel/src/cowrie/.direnv/python-3.9.0/lib/python3.9/site-packages/wokkel/muc.py", line 25, in <module>
    from wokkel import data_form, generic, iwokkel, xmppim
  File "/Users/michel/src/cowrie/.direnv/python-3.9.0/lib/python3.9/site-packages/wokkel/data_form.py", line 20, in <module>
    from twisted.python.compat import iteritems, unicode, _PY3
ImportError: cannot import name '_PY3' from 'twisted.python.compat' (unknown location)
>>> 
```
